### ISSUE TITLE
 ImportError: cannot import name 'ecdsa_to_hex'

### ISSUE THREAD

**Issue by gtyson** [Storj/storj-python-sdk#132]
```
2017-08-06T18:21:50.090158+00:00 app[worker.1]: Traceback (most recent call last):
2017-08-06T18:21:50.090178+00:00 app[worker.1]:   File "inno.py", line 14, in <module>
2017-08-06T18:21:50.090320+00:00 app[worker.1]:     import storj
2017-08-06T18:21:50.090321+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/storj/__init__.py", line 12, in <module>
2017-08-06T18:21:50.090424+00:00 app[worker.1]:     from .http import Client
2017-08-06T18:21:50.090425+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/storj/http.py", line 26, in <module>
2017-08-06T18:21:50.090515+00:00 app[worker.1]:     from api import ecdsa_to_hex
2017-08-06T18:21:50.090517+00:00 app[worker.1]: ImportError: cannot import name 'ecdsa_to_hex'
```
I checked the file api.py , it has the function 'ecdsa_to_hex' but it still isnt working.

**Comment by steenzout** [comment]
@gtyson I've just released a new version.

Please update your local installation and try again.
