### ISSUE TITLE
File Download Functionality Broken

### ISSUE THREAD

**Issue by sibblegp** [storj/storj-python-sdk#134]
Even when I add skip and Limit to the already broken file download functionality, I get this new error:

`Traceback (most recent call last):
  File "<input>", line 1, in <module>
    storj.FileManager('3ec6f7149c8ccc4afe3a2ed9').download('3ec6f7149c8ccc4afe3a2ed9', '6562f709227e7719010faa36')
  File "/apps/edgestore/ed_store/lib/python3.6/site-packages/storj/__init__.py", line 140, in download
    get_client().file_download(bucket_id, file_id)
  File "/apps/edgestore/ed_store/lib/python3.6/site-packages/storj/http.py", line 40, in decorator
    return func(*args, **kwargs)
  File "/apps/edgestore/ed_store/lib/python3.6/site-packages/storj/http.py", line 421, in file_download
    ws.connect()
  File "/apps/edgestore/ed_store/lib/python3.6/site-packages/ws4py/client/__init__.py", line 237, in connect
    self.process_response_line(response_line)
  File "/apps/edgestore/ed_store/lib/python3.6/site-packages/ws4py/client/__init__.py", line 302, in process_response_line
    raise HandshakeError("Invalid response status: %s %s" % (code, status))
ws4py.exc.HandshakeError: Invalid response status: b'405' b'Connection Not Upgraded'`

Apparently our Websocket connection doesn't even work.

Is this maintained at all?

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
